name: Build

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  mod_name: Creepers

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: npm install
    - run: npm run buildpug production
    - run: npm run buildsource
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.mod_name }}
        path: |
          About
          Assemblies
          Defs
          Patches
          Textures
          Sounds
          News
          *.md
